# yaml-language-server: $schema=workflow.schema.json
---
name: My Workflow
on:
  execute:
    inputs:
      novnc_dir:
        type: string
        label: Default noVNC installation directory
        hidden: true
        placeholder: __WORKDIR__/pw/bootstrap/noVNC-1.3.0
        optional: true
      novnc_tgz:
        type: string
        label: Path to noVNC TGZ
        hidden: true
        placeholder: /swift-pw-bin/apps/noVNC-1.3.0.tgz
        optional: true
      service:
        type: group
        label: Service
        items:
          name:
            type: dropdown
            label: Select remote display protocol
            options:
              - label: VNC Server
                value: turbovnc
              - label: Nice DCV
                value: nicedcv
              - label: Scyld Cloud Workstation
                value: scw
            tooltip:
              - Make sure the display protocol is installed in the host!
            default: turbovnc
            optional: true
        collapsed: true
      pwrl_host:
        type: group
        label: Desktop Host
        items:
          resource:
            type: compute-clusters
            label: Service host
            include-workspace: true
            tooltip:
              - Resource to host the service
          nports:
            type: string
            label: Number of Ports to Reserve
            hidden: true
            default: '1'
            optional: true
          jobschedulertype:
            type: dropdown
            label: Select Controller, SLURM Partition or PBS Queue
            options:
              - value: CONTROLLER
                label: Controller
              - value: SLURM
                label: SLURM Partition
              - value: PBS
                label: PBS Queue
            tooltip:
              - Job will submitted using SSH, sbatch or qsub, respectively
          _sch__dd_partition_e_:
            type: slurm-partitions
            label: SLURM partition
            hidden: "{{ 'SLURM' !== inputs.pwrl_host.jobschedulertype }}"
            tooltip:
              - >-
                Partition to submit the interactive job. Leave empty to let SLURM pick
                the optimal option.
            resource: "{{ inputs.pwrl_host.resource }}"
            optional: true
          scheduler_directives_slurm:
            type: string
            label: Scheduler directives
            hidden: "{{ 'SLURM' !== inputs.pwrl_host.jobschedulertype }}"
            tooltip:
              - >-
                e.g. --mem=1000;--gpus-per-node=1 - Use the semicolon character ; to
                separate parameters. Do not include the SBATCH keyword.
            optional: true
          _sch__d_q___:
            type: string
            label: PBS queue
            hidden: "{{ 'PBS' !== inputs.pwrl_host.jobschedulertype }}"
            tooltip:
              - >-
                Queue to submit the interactive job. Must select one! Use [qstat -f
                -Q] to list all queues on the system
          scheduler_directives_pbs:
            type: string
            label: Scheduler directives
            hidden: "{{ 'PBS' !== inputs.pwrl_host.jobschedulertype }}"
            tooltip:
              - >-
                e.g. -l mem=1000;-l nodes=1:ppn=4 - Use the semicolon character ; to
                separate parameters. Do not include the PBS keyword.
            optional: true
        collapsed: false

jobs:
  first-job:
    steps:
      - name: Run the main.sh
        run: ./main.sh
